export interface User {
    nome?:string,
    nomeUrl?: string,
    whatsapp?: string,
    uid?: string,
    rua?: string,
    bairro?: string,
    numero?:string,
    cidade?: string,
    estado?: string,
    cep?: string,
    email?: string,
    autorizado?: boolean,
    taxaEntrega?: number,
    expediente?: string[],
    horario?: string,
    pagamentos?: string[],
    cupom?: string,
    cupomStatus?: boolean,
    desconto?: number,
    categorias? : string[],
    dataInicio?: number,
    receberPorWhatsapp?: boolean,
    endereco?: string,
    minTaxa?: number,
    freteDinamico?:boolean,
    enderecosFixos?: string[]
}
